// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroFuncionarios.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250524150523_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataDesligamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cargo = "Analista",
                            DataAdmissao = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ana Souza"
                        },
                        new
                        {
                            Id = 2,
                            Cargo = "Gerente",
                            DataAdmissao = new DateTime(2019, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Carlos Lima"
                        },
                        new
                        {
                            Id = 3,
                            Cargo = "Assistente",
                            DataAdmissao = new DateTime(2021, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDesligamento = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fernanda Dias"
                        },
                        new
                        {
                            Id = 4,
                            Cargo = "Analista",
                            DataAdmissao = new DateTime(2022, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "João Pedro"
                        },
                        new
                        {
                            Id = 5,
                            Cargo = "Coordenadora",
                            DataAdmissao = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDesligamento = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Luciana Braga"
                        },
                        new
                        {
                            Id = 6,
                            Cargo = "Analista",
                            DataAdmissao = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Marcos Silva"
                        },
                        new
                        {
                            Id = 7,
                            Cargo = "Gerente",
                            DataAdmissao = new DateTime(2017, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Juliana Rocha"
                        },
                        new
                        {
                            Id = 8,
                            Cargo = "Assistente",
                            DataAdmissao = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Rafael Costa"
                        },
                        new
                        {
                            Id = 9,
                            Cargo = "Analista",
                            DataAdmissao = new DateTime(2020, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Beatriz Martins"
                        },
                        new
                        {
                            Id = 10,
                            Cargo = "Técnico",
                            DataAdmissao = new DateTime(2016, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataDesligamento = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Eduardo Nunes"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
